[workspace]
#members = ["ccg_bot_bin", "ccg_bot_sys"] #renable as, and when, the ccg_bot_sys crate is needed
members = ["ccg_bot_bin"]

[profile.dev]
opt-level = 3
debug = 2
codegen-units = 64
incremental = true